week1/week1demo/config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get '/blog', to: 'posts#index'
  devise_for :users
  root 'posts#index'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

week1/week1demo/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, allow_blank: false
end

week1/week1demo/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :thumbnail
  has_one_attached :banner
  has_many :comments, dependent: :destroy
  has_rich_text :body
  validates :title, length: {minimum: 5}
  validates :body, length: {minimum: 25}
  self.per_page = 10
  
  def optimized_image (image, x,y)
    return image.variant(resize_to_fill: [x, y]).processed
  end
end

week1/week1demo/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy

  def username
    return self.email.split('@')[0].capitalize
  end
end

week1/week1demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :is_admin?
    helper_method :is_admin!
    private
    def is_admin?
        if current_user
            return current_user.admin
        else
            return false
        end
    end
    def is_admin!
        if current_user && current_user.admin
        else
            redirect_to root_path
        end
    end
end

week1/week1demo/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save

  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
  def set_post
    @post = Post.find(params[:post_id])
  end
end

week1/week1demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

week1/week1demo/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Dean's Blog</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class:'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to "About", about_path, class:'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <%= current_user.username %>
        </a>
        <div
          class="dropdown-menu dropdown-menu-right"
          aria-labelledby="navbarDropdown"
        >
          <% if current_user.admin %> <%= link_to "New Post", new_post_path,
          class:'dropdown-item' %> <% end %> <%= link_to "Account Settings",
          edit_user_registration_path, class:'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", destroy_user_session_path, method: :delete,
          class:'dropdown-item' %>
        </div>
      </li>
      <% else %>

      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

week1/week1demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Week1demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>