week18/hotwire-todo/config/routes.rb
Rails.application.routes.draw do
  resources :todos
  get '/completed/:id', to: 'completed#update', as: 'update_completed'
  root to: 'todos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

week18/hotwire-todo/app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  after_create_commit { broadcast_prepend_to 'todos' }
  after_update_commit { broadcast_replace_to 'todos' }
  after_destroy_commit { broadcast_remove_to 'todos' }
end

week18/hotwire-todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

week18/hotwire-todo/app/controllers/completed_controller.rb
class CompletedController < ApplicationController
  def update
    @todo = Todo.find(params[:id])
    @todo.completed = !@todo.completed
    @todo.save
    # if we don't type respond, we get the 406 error code. 
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace(@todo) }
      format.html         { redirect_to todos_url }
    end
  end
end

week18/hotwire-todo/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[show edit update destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
    @todo = Todo.new
  end

  # GET /todos/1
  # GET /todos/1.json
  def show; end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit; end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@todo, partial: 'todos/form', locals: { todo: @todo })}
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def todo_params
    params.require(:todo).permit(:title, :completed)
  end
end

week18/hotwire-todo/app/helpers/application_helper.rb
module ApplicationHelper
end

week18/hotwire-todo/app/helpers/completed_helper.rb
module CompletedHelper
end

week18/hotwire-todo/app/helpers/todos_helper.rb
module TodosHelper
end

week18/hotwire-todo/app/views/todos/_form.html.erb
<%= form_with(model: todo, id: dom_id(todo)) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

week18/hotwire-todo/app/views/todos/_todo.html.erb
<%= turbo_frame_tag dom_id(todo) do %>
<div class="card">
    <div class="card-body <%= todo.completed ? 'completed' : 'not-completed' %>">
        <%= todo.title %></br>
        <div class="btn-group float-right">
            <%= link_to "Complete", update_completed_path(id: todo.id, todo: todo), class: 'btn btn-secondary' %>
            <%= link_to "Edit", edit_todo_path(todo), class:'btn btn-warning' %>
            <%= button_to "Destroy", todo, method: :delete, class:'btn btn-danger' %>
        </div>
    </div>
</div>
<% end %>

week18/hotwire-todo/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= turbo_frame_tag dom_id(@todo) do %>
<div class="card">
    <div class="card-body <%= @todo.completed ? 'completed' : 'not-completed' %>">
        <%= render 'form', todo: @todo %>
        <%= link_to "Cancel", @todo %>
    </div>
</div>



<% end %>

week18/hotwire-todo/app/views/todos/index.html.erb
<h1>Hotwire Todo List</h1>

<%= turbo_stream_from "todos" %>

<%= turbo_frame_tag "todo_form" do %>
  <%= render 'form', todo: @todo %>
<% end %>

<%= turbo_frame_tag "todos" do %>
  <%= render @todos %>
<% end %>

week18/hotwire-todo/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

week18/hotwire-todo/app/views/todos/show.html.erb
<%= turbo_frame_tag dom_id(@todo) do %>
  <%= render @todo %>
<% end %>