week6/week6demo_final/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'games#index'
  post 'games/search'
  resources :genres
  resources :games do
    member do
      put 'like' => 'games#like'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

week6/week6demo_final/app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_and_belongs_to_many :genres
  has_one_attached :thumbnail
  has_rich_text :review
  acts_as_votable

  def resized_thumbnail
    thumbnail.variant(resize: '240x135!')
  end
end

week6/week6demo_final/app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_and_belongs_to_many :games
end

week6/week6demo_final/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_voter
  def username
    email.split('@')[0].capitalize
  end
end

week6/week6demo_final/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_featured
  helper_method :is_admin!

  def set_featured
    @featured = Genre.where(feature_in_navbar: true).order('name ASC')
  end

  private

  def is_admin!
    redirect_to root_path unless current_user&.admin
  end
end

week6/week6demo_final/app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy like]
  before_action :set_genres, except: %i[show destroy]
  before_action :is_admin!, except: %i[show index]
  before_action :authenticate_user!, only: [:like]

  # GET /games
  # GET /games.json
  def index
    set_games_and_genre_with_criteria(params[:genre], '')
  end

  def search
    set_games_and_genre_with_criteria(params[:genre], params[:order])
  end

  # GET /games/1
  # GET /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    if current_user.voted_for? @game
      @game.unliked_by current_user
    else
      @game.liked_by current_user
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  def set_genres
    @genres = Genre.all
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:title, :body, :review, :rating, :thumbnail, genre_ids: [])
  end

  def set_games_and_genre_with_criteria(requested_genre, requested_order)
    if requested_genre.nil? || requested_genre.eql?('All')
      games_by_genre = Game.all
      @genre_name = 'All'
    else
      games_by_genre = filter_games_by_genre(requested_genre)
      @genre_name = requested_genre
    end
    order_games(requested_order, games_by_genre)
  end

  def filter_games_by_genre(genre_name)
    @genre = Genre.find_by(name: genre_name)
    games = if @genre.nil?
              Game.none
            else
              @genre.games
    end
  end

  def order_games(_order, _games)
    @games = case _order
             when 'A-Z'
               _games.order('title ASC')
             when 'Z-A'
               _games.order('title DESC')
             when 'Highest Rating First'
               _games.order('rating DESC')
             when 'Lowest Rating First'
               _games.order('rating ASC')
             when 'Newest First'
               _games.order('created_at DESC')
             when 'Oldest First'
               _games.order('created_at ASC')
             else
               _games.order('title ASC')
    end
  end
end

week6/week6demo_final/app/controllers/genres_controller.rb
# frozen_string_literal: true

class GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]
  before_action :is_admin!
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show; end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit; end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genres_path, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genre
    @genre = Genre.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genre_params
    params.require(:genre).permit(:name, :feature_in_navbar)
  end
end

week6/week6demo_final/app/helpers/games_helper.rb
module GamesHelper
end

week6/week6demo_final/app/helpers/genres_helper.rb
module GenresHelper
end

week6/week6demo_final/app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
<% if game.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

    <ul>
        <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>

<div class="field">
    <%= form.label :review %>
    <%= form.rich_text_area :review %>
</div>

<div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
</div>

<div class="field">
    <%= form.label :genres %>
    <%= form.collection_select :genre_ids, @genres, :id, :name, {}, {multiple: true} %>
</div>

<div class="field">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

week6/week6demo_final/app/views/games/_genres.html.erb
<h1><%= link_to @genre_name, root_path %></h1>
<div id="games">
    <% @games.each do |game| %>
    <% if game.thumbnail.attached? %>
    <% if params[:genre] %>
    <%= link_to image_tag(game.resized_thumbnail), game_path(game, genre: params[:genre]) %>
    <% else %>
    <%= link_to image_tag(game.resized_thumbnail), game %>
    <% end %>
    <% end %>
    <% end %>
</div>

week6/week6demo_final/app/views/games/_like_text.html.erb
<% vote_text = current_user&.voted_for?(game) ? "Unlike" : "Like"%>
<%= link_to vote_text, like_game_path(game), 
method: :put, remote: :true, class: 'like-post' %>

week6/week6demo_final/app/views/games/_likes.html.erb
<%= pluralize(game.get_upvotes.size, 'Like') %>

week6/week6demo_final/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

week6/week6demo_final/app/views/games/index.html.erb
<div class="search-container">
    <%= form_tag(games_search_path, remote: true) do %>
    <div class="container form-group">

        <div class="row">

            <div class="col-5" style="padding:0px">
                <%= select_tag :genre, options_from_collection_for_select(
                @genres.to_a.unshift(Genre.new(id: 0, name: "All")),
            "name",
            "name",
            "0"), class:'form-control' %>
            </div>
            <div class="col-5" style="padding:0px">
                <%= select_tag :order, options_for_select([
                "A-Z",
                "Z-A",
                "Highest Rating First",
                "Lowest Rating First",
                "Newest First",
                "Oldest First"]),
        {include_blank: "Order", class:'form-control'} %>
            </div>
            <div class="col-2" style="padding:0px">
                <%= submit_tag "Search", class:'btn btn-secondary' %>
            </div>
        </div>
    </div>
    <% end %>
</div>


<div id="genres">
    <%= render 'games/genres' %>
</div>

week6/week6demo_final/app/views/games/like.js.erb
$("#like-count").html("<%= j render 'games/likes', game: @game %>");
$("#like-text").html("<%= j render 'games/like_text', game: @game %>");

week6/week6demo_final/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

week6/week6demo_final/app/views/games/search.js.erb
var genres = document.getElementById("genres");
var games = document.getElementById("games")

genres.innerHTML = "<%= j render 'games/genres' %>";

week6/week6demo_final/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
        <div class="col-4">
            <%= image_tag(@game.thumbnail, class:'img-fluid') if @game.thumbnail.attached? %>
            <div class="row">
                <div class="col-12">
                    <h4>
                        [<%= @game.rating %>/10]
                    </h4>
                </div>
                <div class="col-12">
                    <h5>
                        <div id="like-count">
                            <%= render 'games/likes', game: @game %>
                        </div>
                        <div id="like-text">
                            <%= render 'games/like_text', game: @game %>
                        </div>
                        <hr />
                    </h5>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h6>This Game Belongs To <%= render 'games/likes', game: @game %>: </h6>
                </div>
                <% @game.genres.each do |genre| %>
                <div class="col-6">
                    <%= link_to genre.name, games_path(genre: genre.name) %>
                </div>
                <% end %>
                <div class="col-12">
                    <% if current_user&.admin%>
                    <%= link_to 'Edit', edit_game_path(@game), class:'btn btn-warning' %>
                    <%= link_to "Delete", @game, method: :delete, class:'btn btn-danger' %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-8">
            <h1>
                <% if params[:genre].nil? %>
                <%= link_to @game.title, root_path %>
                <% else %>
                <%= link_to @game.title, root_path(genre: params[:genre]) %>
                <% end %>
            </h1>


            <div class="container">
                <%= @game.review %>
            </div>

        </div>

    </div>
</div>